Added daemonize flag to lupulo_start and the create_log to lupulo_create

diff --git a/bin/lupulo_start b/bin/lupulo_start
--- a/bin/lupulo_start
+++ b/bin/lupulo_start
@@ -10,13 +10,28 @@ then
     then
         echo "[!] YOU MIGHT NEED SUPERUSER PERMISSIONS DEPENDING ON THE LISTENER YOU USE."
     fi
+    if [ ! -f settings.py ]
+    then
+        echo "You need to execute lupulo from a valid project directory."
+        exit 1
+    fi
 
     command="from lupulo.settings import settings; print settings['lupulo_cwd']"
     path=$(python2 -c "$command")
 
     dir=$(realpath ./)
 
-    LUPULO_PROJECT_DIR=$dir twistd -ny "$path/startup.tac"
+    if [ $# -gt 0 ]
+    then
+        if [ $1 == '--daemonize' ]
+        then
+            LUPULO_PROJECT_DIR=$dir twistd -y "$path/startup.tac"
+        else
+            echo "The parameter $1 is invalid."
+        fi
+    else
+        LUPULO_PROJECT_DIR=$dir twistd -ny "$path/startup.tac"
+    fi
 else
     echo "You need a python2 interpreter."
 fi
